# tests/test_sources.py
import json

import pytest
from pydantic import BaseModel

from app.sources import (
    SourceSink, build_source, is_source_tool, wrap_tool)
from harness.tools.base import Tool
from harness.types import ToolOutput


# ---------- build_source：各类型工具 ----------

def test_search_knowledge_extracts_filenames_deduped():
    result = "[1]（来源：bio.pdf） 光合作用……\n[2]（来源：bio.pdf） 又一段\n[3]（来源：chem.md） 化学"
    d = build_source("search_knowledge", {"query": "光合"}, result)
    assert d["type"] == "knowledge"
    assert d["label"] == "bio.pdf、chem.md"   # 去重且保序


def test_search_knowledge_empty_is_none():
    assert build_source("search_knowledge", {}, "（未在知识库中检索到相关内容）") is None


def test_search_knowledge_hits_without_source_metadata():
    d = build_source("search_knowledge", {}, "[1] 一段没有来源标注的文本")
    assert d["type"] == "knowledge" and d["label"] == "知识库检索"


def test_search_memory_is_typed_memory_not_knowledge():
    """记忆检索归 memory，不能混进 knowledge——前端据此分色、且 knowledge 会跳知识库页。"""
    d = build_source("search_memory", {"query": "偏好"}, "[1] 用户偏好简洁回答")
    assert d["type"] == "memory"
    assert d["label"] == "长期记忆"


def test_search_memory_empty_is_none():
    assert build_source("search_memory", {}, "（未检索到相关的长期记忆）") is None


def test_browse_extracts_title_and_url():
    result = "标题：光合作用 - 维基百科\n最终URL：https://zh.wikipedia.org/wiki/光合作用\n\n正文……"
    d = build_source("browse", {"url": "https://zh.wikipedia.org/wiki/光合作用"}, result)
    assert d["type"] == "web"
    assert d["label"] == "光合作用 - 维基百科"
    assert d["url"] == "https://zh.wikipedia.org/wiki/光合作用"


def test_http_request_labels_domain():
    # 刻意不用 example.com：它是 RFC 2606 保留域名，已被 looks_placeholder_page 判为
    # 无效抓取而不记源。这里测的是「域名标签提取」，换个真实域名即可。
    d = build_source("http_request", {"url": "https://www.wikipedia.org/a/b?x=1"}, "HTTP 200\n<html>")
    assert d["type"] == "web" and d["label"] == "wikipedia.org"
    assert d["url"] == "https://www.wikipedia.org/a/b?x=1"


def test_http_request_non_200_is_none():
    # 非 200（如被 CDN 拒的 403）不算有效来源
    assert build_source("http_request", {"url": "https://x.com"}, "HTTP 403\nForbidden") is None


def test_http_request_cloudfront_block_is_none():
    # 即便状态码 200，CloudFront 拦截页（The request could not be satisfied）也不记源
    r = ("HTTP 200\n标题：ERROR: The request could not be satisfied\n"
         "最终URL：https://x.com\n\nThe request could not be satisfied. Generated by cloudfront")
    assert build_source("http_request", {"url": "https://x.com"}, r) is None


def test_http_request_empty_body_is_none():
    r = "HTTP 200\n标题：某页\n最终URL：https://x.com\n\n（无可提取正文）"
    assert build_source("http_request", {"url": "https://x.com"}, r) is None


def test_browse_cloudfront_block_is_none():
    r = ("标题：ERROR: The request could not be satisfied\n最终URL：https://x.com\n\n"
         "The request could not be satisfied. Generated by cloudfront (CloudFront)")
    assert build_source("browse", {"url": "https://x.com"}, r) is None


def test_browse_no_content_is_none():
    assert build_source("browse", {"url": "https://x.com"}, "（页面无可提取正文）标题：空页") is None


def test_sample_questions_counts_from_json():
    result = json.dumps([{"stem": "q1"}, {"stem": "q2"}, {"stem": "q3"}], ensure_ascii=False)
    d = build_source("sample_questions", {"count": 5}, result)
    assert d["type"] == "question" and "3" in d["label"]


def test_sample_questions_empty_is_none():
    assert build_source("sample_questions", {}, "题库为空。请提醒用户……") is None


def test_read_attachment_extracts_filename():
    d = build_source("read_attachment", {"attachment_id": "a1"}, "「讲义.pdf」内容：\n第一章……")
    assert d["type"] == "attachment" and d["label"] == "讲义.pdf"


def test_read_attachment_missing_is_none():
    assert build_source("read_attachment", {}, "未找到该附件（attachment_id 有误）") is None


def test_recall_episodes():
    assert build_source("recall_episodes", {}, "[1] 上次这样做成功了")["type"] == "memory"
    assert build_source("recall_episodes", {}, "（无相关历史经验）") is None


def test_code_execution():
    d = build_source("run_python", {"code": "print(1)"}, "1\n")
    assert d["type"] == "code" and d["label"] == "Python 代码执行"


def test_mcp_tool_parsed():
    d = build_source("mcp__weather__get_forecast", {"city": "上海"}, "晴 28℃")
    assert d["type"] == "mcp" and d["label"] == "weather · get_forecast"


def test_non_source_tool_is_none():
    assert build_source("calculator", {"expr": "1+1"}, "2") is None
    assert build_source("update_plan", {}, "已更新") is None
    assert build_source("save_download", {}, "已保存") is None


def test_is_source_tool():
    assert is_source_tool("search_knowledge")
    assert is_source_tool("mcp__x__y")
    assert not is_source_tool("calculator")


# ---------- SourceSink：编号 / 去重 / 快照 ----------

def test_sink_numbers_and_dedupes():
    sink = SourceSink()
    assert sink.record({"type": "web", "label": "A", "url": "http://a"}) == 1
    assert sink.record({"type": "knowledge", "label": "bio.pdf"}) == 2
    # 同 URL → 复用编号 1，不新增
    assert sink.record({"type": "web", "label": "A2", "url": "http://a"}) == 1
    snap = sink.snapshot()
    assert [s["index"] for s in snap] == [1, 2]


def test_sink_reset_clears():
    sink = SourceSink()
    sink.record({"type": "web", "label": "A", "url": "http://a"})
    sink.reset()
    assert sink.snapshot() == []
    assert sink.record({"type": "knowledge", "label": "x"}) == 1


# ---------- wrap_tool：接地标注 + 记源 + 报错不记源 ----------

class _FakeSearch(Tool):
    name = "search_knowledge"
    description = "fake"

    class Params(BaseModel):
        query: str

    def __init__(self, result):
        self._result = result

    async def run(self, params):
        if isinstance(self._result, Exception):
            raise self._result
        return self._result


async def test_wrap_appends_marker_and_records():
    sink = SourceSink()
    wrapped = wrap_tool(_FakeSearch("[1]（来源：bio.pdf） 内容"), sink)
    out = await wrapped.run(wrapped.Params(query="光合"))
    assert "参考来源 [1]" in out
    assert "bio.pdf" in out
    snap = sink.snapshot()
    assert len(snap) == 1 and snap[0]["type"] == "knowledge"


async def test_wrap_tooloutput_preserves_followup():
    sink = SourceSink()

    class _FakeAtt(Tool):
        name = "read_attachment"
        description = "fake"

        class Params(BaseModel):
            attachment_id: str

        async def run(self, params):
            return ToolOutput(text="「x.pdf」内容：正文", follow_up=["FU"])

    wrapped = wrap_tool(_FakeAtt(), sink)
    out = await wrapped.run(wrapped.Params(attachment_id="a1"))
    assert isinstance(out, ToolOutput)
    assert "参考来源 [1]" in out.text and out.follow_up == ["FU"]


async def test_wrap_error_does_not_record():
    sink = SourceSink()
    wrapped = wrap_tool(_FakeSearch(RuntimeError("boom")), sink)
    with pytest.raises(RuntimeError):
        await wrapped.run(wrapped.Params(query="x"))
    assert sink.snapshot() == []


async def test_wrap_empty_result_no_marker_no_record():
    sink = SourceSink()
    wrapped = wrap_tool(_FakeSearch("（未在知识库中检索到相关内容）"), sink)
    out = await wrapped.run(wrapped.Params(query="x"))
    assert "参考来源" not in out
    assert sink.snapshot() == []


def test_wrap_non_source_tool_passthrough():
    sink = SourceSink()

    class _Calc(Tool):
        name = "calculator"
        description = "c"

        class Params(BaseModel):
            expr: str

        async def run(self, params):
            return "2"

    calc = _Calc()
    assert wrap_tool(calc, sink) is calc   # 非来源工具原样返回


# ---------- 记源暂停：交付门内部的工具调用不算「参考来源」 ----------

class _FakePy(Tool):
    """交付门 _run_code_blocks 会从同一个（已包记源层的）registry 取它来跑答案里的代码块。"""
    name = "run_python"
    description = "fake"

    class Params(BaseModel):
        code: str

    async def run(self, params):
        return "stdout:\n42\n(exit 0)"


async def test_paused_sink_records_nothing_and_appends_no_marker():
    # 用户从没看见 AI 执行过这段代码——它是交付门的后台校验行为，不该冒充成参考来源
    sink = SourceSink()
    wrapped = wrap_tool(_FakePy(), sink)
    with sink.paused():
        out = await wrapped.run(wrapped.Params(code="print(6*7)"))
    assert sink.snapshot() == []
    assert "参考来源" not in out          # 标注也不能加：校验器还要解析这段结果


async def test_sink_records_again_after_pause_exits():
    sink = SourceSink()
    wrapped = wrap_tool(_FakePy(), sink)
    with sink.paused():
        await wrapped.run(wrapped.Params(code="print(1)"))
    out = await wrapped.run(wrapped.Params(code="print(2)"))
    assert len(sink.snapshot()) == 1 and "参考来源 [1]" in out


async def test_pause_restores_on_exception():
    sink = SourceSink()
    try:
        with sink.paused():
            raise RuntimeError("校验器炸了")
    except RuntimeError:
        pass
    wrapped = wrap_tool(_FakePy(), sink)
    out = await wrapped.run(wrapped.Params(code="print(1)"))
    assert len(sink.snapshot()) == 1 and "参考来源 [1]" in out   # 异常没把 sink 卡在暂停态


async def test_pause_is_reentrant():
    sink = SourceSink()
    wrapped = wrap_tool(_FakePy(), sink)
    with sink.paused():
        with sink.paused():
            await wrapped.run(wrapped.Params(code="print(1)"))
        await wrapped.run(wrapped.Params(code="print(2)"))   # 内层退出不该提前恢复
    assert sink.snapshot() == []


async def test_paused_http_fetch_is_not_credited_as_source():
    # facts 核查去抓答案里引用的 URL：模型只是写了个链接（可能是编的）、从没读过它，
    # 不能因为交付门核实了一下就把它「认证」成参考来源
    class _FakeHttp(Tool):
        name = "http_request"
        description = "fake"

        class Params(BaseModel):
            url: str

        async def run(self, params):
            return "HTTP 200\n标题：某页\n最终URL：https://x.com/a\n\n正文"

    sink = SourceSink()
    wrapped = wrap_tool(_FakeHttp(), sink)
    with sink.paused():
        await wrapped.run(wrapped.Params(url="https://x.com/a"))
    assert sink.snapshot() == []


# ---------- 占位/停放域名不记源 ----------

def test_browse_placeholder_domain_is_none():
    """抓取成功但落在 example.com：不是真实资料来源，不该出现在「参考来源」里。"""
    r = ("标题：Example Domain\n最终URL：https://example.com/ai-agent-advancements\n\n"
         "This domain is for use in documentation examples without needing permission.")
    assert build_source("browse", {"url": "https://example.com/ai-agent-advancements"}, r) is None


def test_http_placeholder_domain_is_none():
    r = "HTTP 200\n标题：Example Domain\n最终URL：https://example.org/x\n\n示例内容"
    assert build_source("http_request", {"url": "https://example.org/x"}, r) is None


def test_browse_real_domain_still_recorded():
    """反向：真实域名不受影响，照常记源（防止改动误伤正常抓取）。"""
    r = "标题：光合作用 - 维基百科\n最终URL：https://zh.wikipedia.org/wiki/光合作用\n\n正文……"
    d = build_source("browse", {"url": "https://zh.wikipedia.org/wiki/光合作用"}, r)
    assert d is not None and d["type"] == "web"


# —— 成品文件的角标剥离：跳过代码块 ——

def test_strip_citations_outside_code_keeps_code_spans():
    from app.sources import strip_citations_outside_code
    src = "见下[1]。\n```py\nx = a[0] + a[1]\n```\n行内 `b[2]` 保留[3]。"
    out = strip_citations_outside_code(src)
    assert "a[0] + a[1]" in out and "`b[2]`" in out     # 代码原样
    assert "[1]" not in out.split("```")[0]             # 正文角标被剥
    assert out.endswith("保留。")


def test_strip_citations_outside_code_empty_and_noop():
    from app.sources import strip_citations_outside_code
    assert strip_citations_outside_code("") == ""
    assert strip_citations_outside_code("没有角标") == "没有角标"


def test_strip_step_markers_removes_only_step_ids():
    from app.sources import strip_step_markers
    # 连同紧邻空格一起吃掉：漏出的形态是「[s2] # 标题」，留前导空格不干净
    assert strip_step_markers("[s2] # 标题 [s10]尾") == "# 标题尾"
    assert strip_step_markers("来源[1]不动") == "来源[1]不动"   # 数字角标归 strip_citations
